"""M6: add highlights to papers and user_marks table

Revision ID: 28cc6f44279b
Revises: 7c8d79d4ca91
Create Date: 2026-08-19 14:23:42.667368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28cc6f44279b'
down_revision: Union[str, Sequence[str], None] = '7c8d79d4ca91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_marks',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('mark_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'mark_type')
    )
    op.add_column('papers', sa.Column('highlights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'highlights')
    op.drop_table('user_marks')
    # ### end Alembic commands ###
