"""M7: add deep_summary to papers

Revision ID: 58e2e53bd581
Revises: 28cc6f44279b
Create Date: 2026-08-19 18:06:37.347913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e2e53bd581'
down_revision: Union[str, Sequence[str], None] = '28cc6f44279b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('deep_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'deep_summary')
    # ### end Alembic commands ###
