"""add match_candidates to papers

Revision ID: 7c8d79d4ca91
Revises: 8c11e11f23ff
Create Date: 2026-08-18 00:28:05.122708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8d79d4ca91'
down_revision: Union[str, Sequence[str], None] = '8c11e11f23ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('match_candidates', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'match_candidates')
    # ### end Alembic commands ###
