"""add stream_key to venues

Revision ID: 8c11e11f23ff
Revises: cfbfc0c03b5f
Create Date: 2026-08-17 17:45:13.179450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c11e11f23ff'
down_revision: Union[str, Sequence[str], None] = 'cfbfc0c03b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('stream_key', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'stream_key')
    # ### end Alembic commands ###
