"""add journal_ref/comment to papers

Revision ID: cfbfc0c03b5f
Revises: 33cfead14f1b
Create Date: 2026-08-17 13:14:22.037376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfbfc0c03b5f'
down_revision: Union[str, Sequence[str], None] = '33cfead14f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('journal_ref', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'comment')
    op.drop_column('papers', 'journal_ref')
    # ### end Alembic commands ###
