"""M8: add citation_count to papers

Revision ID: f05569ab478b
Revises: 58e2e53bd581
Create Date: 2026-08-19 18:33:35.890414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05569ab478b'
down_revision: Union[str, Sequence[str], None] = '58e2e53bd581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('citation_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'citation_count')
    # ### end Alembic commands ###
